from fastapi import APIRouter

from endpoint.generate.aspect import aspect_generate_router
from endpoint.generate.backstory import backstory_generate_router
from endpoint.generate.group_reasoning_style import group_reasoning_style_generate_router
from endpoint.generate.life_event import life_event_generate_router
from endpoint.generate.persona_fact import persona_fact_generate_router
from endpoint.generate.persona_objective_description import persona_objective_description_generate_router
from endpoint.generate.physical_description import physical_description_generate_router
from endpoint.generate.reasoning import reasoning_generate_router
from endpoint.generate.relationship import relationship_generate_router
from endpoint.generate.self_description_conversation import self_description_conversation_generate_router
from endpoint.generate.speech import speech_profile_generate_router
from endpoint.generate.speech_sample import speech_sample_generate_router
from endpoint.generate.story import story_generate_router

persona_generate_router = APIRouter(prefix="/{universe_id}/persona")
persona_generate_router.include_router(backstory_generate_router)
persona_generate_router.include_router(physical_description_generate_router)
persona_generate_router.include_router(life_event_generate_router)
persona_generate_router.include_router(speech_profile_generate_router)
persona_generate_router.include_router(speech_sample_generate_router)
persona_generate_router.include_router(story_generate_router)
persona_generate_router.include_router(reasoning_generate_router)
persona_generate_router.include_router(relationship_generate_router)
persona_generate_router.include_router(group_reasoning_style_generate_router)
persona_generate_router.include_router(persona_fact_generate_router)
persona_generate_router.include_router(persona_objective_description_generate_router)
persona_generate_router.include_router(self_description_conversation_generate_router)



